--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-30 18:19:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16391)
-- Name: caixa2025; Type: SCHEMA; Schema: -; Owner: caixa_adm
--

CREATE SCHEMA caixa2025;


ALTER SCHEMA caixa2025 OWNER TO caixa_adm;

--
-- TOC entry 2 (class 3079 OID 16395)
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- TOC entry 4958 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- TOC entry 278 (class 1255 OID 24626)
-- Name: relatorio_mensal(integer, integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.relatorio_mensal(p_ano integer, p_mes integer) RETURNS TABLE(categoria character varying, quantidade bigint, valor_total numeric)
    LANGUAGE plpgsql
    AS $$
BEGIN
    RETURN QUERY
    SELECT 
        c.nome::VARCHAR(50) AS categoria,
        COUNT(*)::BIGINT AS quantidade,
        SUM(m.valor)::DECIMAL(10, 2) AS valor_total
    FROM movimentacoes m
    JOIN categorias c ON m.categoria_id = c.id
    WHERE EXTRACT(YEAR FROM m.data_movimentacao) = p_ano
      AND EXTRACT(MONTH FROM m.data_movimentacao) = p_mes
      AND m.tipo = 'SAIDA'
    GROUP BY c.nome
    ORDER BY valor_total DESC;
END;
$$;


ALTER FUNCTION public.relatorio_mensal(p_ano integer, p_mes integer) OWNER TO postgres;

--
-- TOC entry 277 (class 1255 OID 24635)
-- Name: update_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
   NEW.atualizado_em = NOW();
   RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_updated_at() OWNER TO postgres;

--
-- TOC entry 276 (class 1255 OID 24577)
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_updated_at_column() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 228 (class 1259 OID 16493)
-- Name: financeiro; Type: TABLE; Schema: caixa2025; Owner: caixa_adm
--

CREATE TABLE caixa2025.financeiro (
    id bigint NOT NULL,
    data date,
    descricao character varying(255),
    tipo_movimento smallint,
    valor numeric(38,2),
    CONSTRAINT financeiro_tipo_movimento_check CHECK (((tipo_movimento >= 0) AND (tipo_movimento <= 1)))
);


ALTER TABLE caixa2025.financeiro OWNER TO caixa_adm;

--
-- TOC entry 227 (class 1259 OID 16492)
-- Name: financeiro_id_seq; Type: SEQUENCE; Schema: caixa2025; Owner: caixa_adm
--

ALTER TABLE caixa2025.financeiro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME caixa2025.financeiro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16469)
-- Name: fluxo_caixa; Type: TABLE; Schema: caixa2025; Owner: postgres
--

CREATE TABLE caixa2025.fluxo_caixa (
    id integer NOT NULL,
    descricao character varying(255) NOT NULL,
    tipo character varying(10) NOT NULL,
    valor numeric(10,2) NOT NULL,
    data_movimentacao date DEFAULT CURRENT_DATE NOT NULL,
    categoria character varying(100),
    criado_em timestamp without time zone DEFAULT now(),
    CONSTRAINT fluxo_caixa_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['entrada'::character varying, 'saida'::character varying])::text[]))),
    CONSTRAINT fluxo_caixa_valor_check CHECK ((valor > (0)::numeric))
);


ALTER TABLE caixa2025.fluxo_caixa OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16468)
-- Name: fluxo_caixa_id_seq; Type: SEQUENCE; Schema: caixa2025; Owner: postgres
--

CREATE SEQUENCE caixa2025.fluxo_caixa_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE caixa2025.fluxo_caixa_id_seq OWNER TO postgres;

--
-- TOC entry 4959 (class 0 OID 0)
-- Dependencies: 223
-- Name: fluxo_caixa_id_seq; Type: SEQUENCE OWNED BY; Schema: caixa2025; Owner: postgres
--

ALTER SEQUENCE caixa2025.fluxo_caixa_id_seq OWNED BY caixa2025.fluxo_caixa.id;


--
-- TOC entry 236 (class 1259 OID 24627)
-- Name: rules; Type: TABLE; Schema: caixa2025; Owner: caixa_adm
--

CREATE TABLE caixa2025.rules (
    descricao character varying(50) NOT NULL,
    criado_em timestamp without time zone DEFAULT now(),
    atualizado_em timestamp without time zone,
    ativo boolean DEFAULT true NOT NULL,
    ult_usuario_mod text
);


ALTER TABLE caixa2025.rules OWNER TO caixa_adm;

--
-- TOC entry 4960 (class 0 OID 0)
-- Dependencies: 236
-- Name: TABLE rules; Type: COMMENT; Schema: caixa2025; Owner: caixa_adm
--

COMMENT ON TABLE caixa2025.rules IS 'regras';


--
-- TOC entry 226 (class 1259 OID 16481)
-- Name: usuarios; Type: TABLE; Schema: caixa2025; Owner: postgres
--

CREATE TABLE caixa2025.usuarios (
    id integer NOT NULL,
    nome character varying(50) NOT NULL,
    senha_hash text NOT NULL
);


ALTER TABLE caixa2025.usuarios OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16480)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: caixa2025; Owner: postgres
--

CREATE SEQUENCE caixa2025.usuarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE caixa2025.usuarios_id_seq OWNER TO postgres;

--
-- TOC entry 4961 (class 0 OID 0)
-- Dependencies: 225
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: caixa2025; Owner: postgres
--

ALTER SEQUENCE caixa2025.usuarios_id_seq OWNED BY caixa2025.usuarios.id;


--
-- TOC entry 239 (class 1259 OID 32831)
-- Name: view_fluxo_caixa; Type: VIEW; Schema: caixa2025; Owner: postgres
--

CREATE VIEW caixa2025.view_fluxo_caixa AS
 SELECT date_trunc('day'::text, (data_movimentacao)::timestamp with time zone) AS periodo,
    sum(
        CASE
            WHEN ((tipo)::text = 'entrada'::text) THEN valor
            ELSE (0)::numeric
        END) AS total_entradas,
    sum(
        CASE
            WHEN ((tipo)::text = 'saida'::text) THEN valor
            ELSE (0)::numeric
        END) AS total_saidas,
    sum(
        CASE
            WHEN ((tipo)::text = 'entrada'::text) THEN valor
            ELSE (- valor)
        END) AS saldo_diario,
    sum(sum(
        CASE
            WHEN ((tipo)::text = 'entrada'::text) THEN valor
            ELSE (- valor)
        END)) OVER (ORDER BY (date_trunc('day'::text, (data_movimentacao)::timestamp with time zone))) AS saldo_acumulado,
    count(*) AS quantidade_transacoes
   FROM caixa2025.fluxo_caixa
  WHERE (data_movimentacao IS NOT NULL)
  GROUP BY (date_trunc('day'::text, (data_movimentacao)::timestamp with time zone))
  ORDER BY (date_trunc('day'::text, (data_movimentacao)::timestamp with time zone));


ALTER VIEW caixa2025.view_fluxo_caixa OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 24581)
-- Name: categorias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias (
    id integer NOT NULL,
    nome character varying(50) NOT NULL,
    descricao text,
    tipo character varying(10) NOT NULL,
    CONSTRAINT categorias_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SAIDA'::character varying])::text[])))
);


ALTER TABLE public.categorias OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 24580)
-- Name: categorias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.categorias_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.categorias_id_seq OWNER TO postgres;

--
-- TOC entry 4962 (class 0 OID 0)
-- Dependencies: 229
-- Name: categorias_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.categorias_id_seq OWNED BY public.categorias.id;


--
-- TOC entry 222 (class 1259 OID 16457)
-- Name: fluxo_caixa; Type: TABLE; Schema: public; Owner: caixa_adm
--

CREATE TABLE public.fluxo_caixa (
    id integer NOT NULL,
    descricao character varying(255) NOT NULL,
    tipo character varying(10) NOT NULL,
    valor numeric(10,2) NOT NULL,
    data_movimentacao date DEFAULT CURRENT_DATE NOT NULL,
    categoria character varying(100),
    criado_em timestamp without time zone DEFAULT now(),
    CONSTRAINT fluxo_caixa_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['entrada'::character varying, 'saida'::character varying])::text[]))),
    CONSTRAINT fluxo_caixa_valor_check CHECK ((valor > (0)::numeric))
);


ALTER TABLE public.fluxo_caixa OWNER TO caixa_adm;

--
-- TOC entry 221 (class 1259 OID 16456)
-- Name: fluxo_caixa_id_seq; Type: SEQUENCE; Schema: public; Owner: caixa_adm
--

CREATE SEQUENCE public.fluxo_caixa_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.fluxo_caixa_id_seq OWNER TO caixa_adm;

--
-- TOC entry 4963 (class 0 OID 0)
-- Dependencies: 221
-- Name: fluxo_caixa_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: caixa_adm
--

ALTER SEQUENCE public.fluxo_caixa_id_seq OWNED BY public.fluxo_caixa.id;


--
-- TOC entry 232 (class 1259 OID 24591)
-- Name: movimentacoes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimentacoes (
    id integer NOT NULL,
    descricao character varying(255) NOT NULL,
    valor numeric(10,2) NOT NULL,
    tipo character varying(10) NOT NULL,
    data_movimentacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    usuario_id integer,
    categoria_id integer,
    CONSTRAINT movimentacoes_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SAIDA'::character varying])::text[])))
);


ALTER TABLE public.movimentacoes OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 24590)
-- Name: movimentacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.movimentacoes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.movimentacoes_id_seq OWNER TO postgres;

--
-- TOC entry 4964 (class 0 OID 0)
-- Dependencies: 231
-- Name: movimentacoes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.movimentacoes_id_seq OWNED BY public.movimentacoes.id;


--
-- TOC entry 238 (class 1259 OID 32823)
-- Name: movimentos_caixa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimentos_caixa (
    id integer NOT NULL,
    data_movimento timestamp without time zone NOT NULL,
    descricao character varying(200),
    tipo_movimento character varying(10),
    valor numeric(10,2) NOT NULL,
    categoria character varying(50),
    forma_pagamento character varying(50),
    CONSTRAINT movimentos_caixa_tipo_movimento_check CHECK (((tipo_movimento)::text = ANY ((ARRAY['entrada'::character varying, 'saida'::character varying])::text[])))
);


ALTER TABLE public.movimentos_caixa OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 32822)
-- Name: movimentos_caixa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.movimentos_caixa_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.movimentos_caixa_id_seq OWNER TO postgres;

--
-- TOC entry 4965 (class 0 OID 0)
-- Dependencies: 237
-- Name: movimentos_caixa_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.movimentos_caixa_id_seq OWNED BY public.movimentos_caixa.id;


--
-- TOC entry 220 (class 1259 OID 16433)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    nome character varying(50) NOT NULL,
    senha_hash text NOT NULL
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16432)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuarios_id_seq OWNER TO postgres;

--
-- TOC entry 4966 (class 0 OID 0)
-- Dependencies: 219
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- TOC entry 235 (class 1259 OID 24622)
-- Name: view_movimentacoes_por_usuario; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.view_movimentacoes_por_usuario AS
 SELECT u.nome AS usuario,
    m.tipo,
    count(*) AS quantidade,
    sum(m.valor) AS valor_total
   FROM (public.movimentacoes m
     JOIN public.usuarios u ON ((m.usuario_id = u.id)))
  GROUP BY u.nome, m.tipo
  ORDER BY u.nome, m.tipo;


ALTER VIEW public.view_movimentacoes_por_usuario OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 24617)
-- Name: view_saidas_por_categoria; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.view_saidas_por_categoria AS
 SELECT c.nome AS categoria,
    count(*) AS quantidade,
    sum(m.valor) AS valor_total
   FROM (public.movimentacoes m
     JOIN public.categorias c ON ((m.categoria_id = c.id)))
  WHERE ((m.tipo)::text = 'SAIDA'::text)
  GROUP BY c.nome
  ORDER BY (sum(m.valor)) DESC;


ALTER VIEW public.view_saidas_por_categoria OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 24613)
-- Name: view_totais_movimentacoes; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.view_totais_movimentacoes AS
 SELECT tipo,
    count(*) AS quantidade,
    sum(valor) AS valor_total
   FROM public.movimentacoes
  GROUP BY tipo;


ALTER VIEW public.view_totais_movimentacoes OWNER TO postgres;

--
-- TOC entry 4741 (class 2604 OID 16472)
-- Name: fluxo_caixa id; Type: DEFAULT; Schema: caixa2025; Owner: postgres
--

ALTER TABLE ONLY caixa2025.fluxo_caixa ALTER COLUMN id SET DEFAULT nextval('caixa2025.fluxo_caixa_id_seq'::regclass);


--
-- TOC entry 4744 (class 2604 OID 16484)
-- Name: usuarios id; Type: DEFAULT; Schema: caixa2025; Owner: postgres
--

ALTER TABLE ONLY caixa2025.usuarios ALTER COLUMN id SET DEFAULT nextval('caixa2025.usuarios_id_seq'::regclass);


--
-- TOC entry 4745 (class 2604 OID 24584)
-- Name: categorias id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias ALTER COLUMN id SET DEFAULT nextval('public.categorias_id_seq'::regclass);


--
-- TOC entry 4738 (class 2604 OID 16460)
-- Name: fluxo_caixa id; Type: DEFAULT; Schema: public; Owner: caixa_adm
--

ALTER TABLE ONLY public.fluxo_caixa ALTER COLUMN id SET DEFAULT nextval('public.fluxo_caixa_id_seq'::regclass);


--
-- TOC entry 4746 (class 2604 OID 24594)
-- Name: movimentacoes id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimentacoes ALTER COLUMN id SET DEFAULT nextval('public.movimentacoes_id_seq'::regclass);


--
-- TOC entry 4750 (class 2604 OID 32826)
-- Name: movimentos_caixa id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimentos_caixa ALTER COLUMN id SET DEFAULT nextval('public.movimentos_caixa_id_seq'::regclass);


--
-- TOC entry 4737 (class 2604 OID 16436)
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- TOC entry 4945 (class 0 OID 16493)
-- Dependencies: 228
-- Data for Name: financeiro; Type: TABLE DATA; Schema: caixa2025; Owner: caixa_adm
--

COPY caixa2025.financeiro (id, data, descricao, tipo_movimento, valor) FROM stdin;
\.


--
-- TOC entry 4941 (class 0 OID 16469)
-- Dependencies: 224
-- Data for Name: fluxo_caixa; Type: TABLE DATA; Schema: caixa2025; Owner: postgres
--

COPY caixa2025.fluxo_caixa (id, descricao, tipo, valor, data_movimentacao, categoria, criado_em) FROM stdin;
1	Venda de produto	entrada	150.00	2024-03-12	Vendas	2025-03-12 14:27:56.077019
2	Pagamento de aluguel	saida	1000.00	2024-03-10	Despesas Fixas	2025-03-12 14:27:56.077019
\.


--
-- TOC entry 4950 (class 0 OID 24627)
-- Dependencies: 236
-- Data for Name: rules; Type: TABLE DATA; Schema: caixa2025; Owner: caixa_adm
--

COPY caixa2025.rules (descricao, criado_em, atualizado_em, ativo, ult_usuario_mod) FROM stdin;
\.


--
-- TOC entry 4943 (class 0 OID 16481)
-- Dependencies: 226
-- Data for Name: usuarios; Type: TABLE DATA; Schema: caixa2025; Owner: postgres
--

COPY caixa2025.usuarios (id, nome, senha_hash) FROM stdin;
1	sjp	$2a$06$FhzhPak65K5eMBjFbn01Jed0i3u5FjNa9DVqPIdK8aeIGqvsnoyX2
2	carmo	$2a$06$NDbOMHTtvYA9cMORoeZ5Ge2z9bAxlHYTRHF6eGVi2UTfteHPbXSNS
3	sitio	$2a$06$fjdHDnWmo0cvarAcIHO4se4.e/CZwueLVCRAHg6Aw2xTu85k7.0TK
4	frg	$2a$06$JTJClPlRF75elYoUqUNvU.WiORR8aQzbLvH5g2UwB.Mw.M9RO6hMC
5	portao	$2a$06$sEvXRWnb9T1sB7p3dwzShOoWqSdcoHAY/Pvn5zWm3ht58DArP9z6e
6	araucaria1	$2a$06$fa3Ru6ELISPdZ3gzYDb1zOI.Tcf97ZJK6PYfN78lT2wW9tt3MG9ne
7	araucaria2	$2a$06$rJIISmzTNwl4u5vsMJKTOe7Zw8wOWA30C53uD.chwfV1kkfbpx4yK
\.


--
-- TOC entry 4947 (class 0 OID 24581)
-- Dependencies: 230
-- Data for Name: categorias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categorias (id, nome, descricao, tipo) FROM stdin;
45	IFOOD	Vendas através do iFood	ENTRADA
46	PAG VIA PIX	Pagamentos recebidos via PIX	ENTRADA
47	DEBITO CIELLO	Vendas no débito - Cielo	ENTRADA
48	CREDITO CIELLO	Vendas no crédito - Cielo	ENTRADA
49	VOUCHER CIELLO	Vendas com voucher - Cielo	ENTRADA
50	DEBITO REDE	Vendas no débito - Rede	ENTRADA
51	CREDITO REDE	Vendas no crédito - Rede	ENTRADA
52	VOUCHER REDE	Vendas com voucher - Rede	ENTRADA
53	TROCO GAVETA	Troco mantido na gaveta	ENTRADA
54	LANCHES CANCELADOS	Lanches cancelados/devolvidos	SAIDA
55	GUARDA	Despesas diversas de guarda	SAIDA
56	LANCHES FUNCIONARIOS	Lanches para funcionários	SAIDA
57	VALE FUNCIONARIO	Vale funcionário 1	SAIDA
58	VALE TRANSPORTE	Vales para transporte	SAIDA
59	DOCES	Despesas com doces	SAIDA
60	DESPESAS/ALMOÇO FUNCIONARIO	Almoço para funcionários	SAIDA
61	SANGRIAS	Retirada de caixa 1	SAIDA
62	COMPUTADOR	Despesas com computador	SAIDA
63	PORCENTAGEM LANCHE	Porcentagem sobre lanches	SAIDA
64	DIARIA FUNCIONARIO	Diária de funcionários	SAIDA
65	TAXA MOTOBOY	Taxas de motoboy	SAIDA
66	BEBIDAS CANCELADAS	Bebidas canceladas/devolvidas	SAIDA
\.


--
-- TOC entry 4939 (class 0 OID 16457)
-- Dependencies: 222
-- Data for Name: fluxo_caixa; Type: TABLE DATA; Schema: public; Owner: caixa_adm
--

COPY public.fluxo_caixa (id, descricao, tipo, valor, data_movimentacao, categoria, criado_em) FROM stdin;
\.


--
-- TOC entry 4949 (class 0 OID 24591)
-- Dependencies: 232
-- Data for Name: movimentacoes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimentacoes (id, descricao, valor, tipo, data_movimentacao, usuario_id, categoria_id) FROM stdin;
\.


--
-- TOC entry 4952 (class 0 OID 32823)
-- Dependencies: 238
-- Data for Name: movimentos_caixa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimentos_caixa (id, data_movimento, descricao, tipo_movimento, valor, categoria, forma_pagamento) FROM stdin;
\.


--
-- TOC entry 4937 (class 0 OID 16433)
-- Dependencies: 220
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, nome, senha_hash) FROM stdin;
1	sjp	$2a$06$XS1D8cd4JDiZq9Msi2wTS.LiOwLMa3c14R72VclE1L1Vq9cAGieR2
2	carmo	$2a$06$SGYbFab6HVtHPmgM2P56mOb3dxANoz9BPlM19DoxKrWxb96nVoDFK
3	sitio	$2a$06$z4qVAWlz/YicuelGoJUKLOeQbA9QTCEdZj0Sdb6FgB0OwmbnyQaT6
4	frg	$2a$06$nC3g7gMMHvD9BZZtueKu9eNq6Mb7ze2QuloqGVXwWD6zdVKWusguy
5	portao	$2a$06$VJ4azIR3tdJ9ksyrAYqlyOm0kTUExhFibXGNjstHX9cAP07ykgAWi
6	araucaria1	$2a$06$rUc/4LNExTbDk03.fs3yzuTsRnj8cWeRfuPABAFyW/RJKGC5V15tu
7	araucaria2	$2a$06$3pJhe5U.nWG9xH44txnOVeRIqfuMmiC432585TIx/6XR8v4fWIO0K
\.


--
-- TOC entry 4967 (class 0 OID 0)
-- Dependencies: 227
-- Name: financeiro_id_seq; Type: SEQUENCE SET; Schema: caixa2025; Owner: caixa_adm
--

SELECT pg_catalog.setval('caixa2025.financeiro_id_seq', 1, false);


--
-- TOC entry 4968 (class 0 OID 0)
-- Dependencies: 223
-- Name: fluxo_caixa_id_seq; Type: SEQUENCE SET; Schema: caixa2025; Owner: postgres
--

SELECT pg_catalog.setval('caixa2025.fluxo_caixa_id_seq', 2, true);


--
-- TOC entry 4969 (class 0 OID 0)
-- Dependencies: 225
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: caixa2025; Owner: postgres
--

SELECT pg_catalog.setval('caixa2025.usuarios_id_seq', 7, true);


--
-- TOC entry 4970 (class 0 OID 0)
-- Dependencies: 229
-- Name: categorias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorias_id_seq', 66, true);


--
-- TOC entry 4971 (class 0 OID 0)
-- Dependencies: 221
-- Name: fluxo_caixa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: caixa_adm
--

SELECT pg_catalog.setval('public.fluxo_caixa_id_seq', 1, false);


--
-- TOC entry 4972 (class 0 OID 0)
-- Dependencies: 231
-- Name: movimentacoes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimentacoes_id_seq', 1, false);


--
-- TOC entry 4973 (class 0 OID 0)
-- Dependencies: 237
-- Name: movimentos_caixa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimentos_caixa_id_seq', 1, false);


--
-- TOC entry 4974 (class 0 OID 0)
-- Dependencies: 219
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 7, true);


--
-- TOC entry 4772 (class 2606 OID 16498)
-- Name: financeiro financeiro_pkey; Type: CONSTRAINT; Schema: caixa2025; Owner: caixa_adm
--

ALTER TABLE ONLY caixa2025.financeiro
    ADD CONSTRAINT financeiro_pkey PRIMARY KEY (id);


--
-- TOC entry 4766 (class 2606 OID 16478)
-- Name: fluxo_caixa fluxo_caixa_pkey; Type: CONSTRAINT; Schema: caixa2025; Owner: postgres
--

ALTER TABLE ONLY caixa2025.fluxo_caixa
    ADD CONSTRAINT fluxo_caixa_pkey PRIMARY KEY (id);


--
-- TOC entry 4768 (class 2606 OID 16490)
-- Name: usuarios usuarios_nome_key; Type: CONSTRAINT; Schema: caixa2025; Owner: postgres
--

ALTER TABLE ONLY caixa2025.usuarios
    ADD CONSTRAINT usuarios_nome_key UNIQUE (nome);


--
-- TOC entry 4770 (class 2606 OID 16488)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: caixa2025; Owner: postgres
--

ALTER TABLE ONLY caixa2025.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4774 (class 2606 OID 24589)
-- Name: categorias categorias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias
    ADD CONSTRAINT categorias_pkey PRIMARY KEY (id);


--
-- TOC entry 4764 (class 2606 OID 16466)
-- Name: fluxo_caixa fluxo_caixa_pkey; Type: CONSTRAINT; Schema: public; Owner: caixa_adm
--

ALTER TABLE ONLY public.fluxo_caixa
    ADD CONSTRAINT fluxo_caixa_pkey PRIMARY KEY (id);


--
-- TOC entry 4780 (class 2606 OID 24598)
-- Name: movimentacoes movimentacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimentacoes
    ADD CONSTRAINT movimentacoes_pkey PRIMARY KEY (id);


--
-- TOC entry 4782 (class 2606 OID 32829)
-- Name: movimentos_caixa movimentos_caixa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimentos_caixa
    ADD CONSTRAINT movimentos_caixa_pkey PRIMARY KEY (id);


--
-- TOC entry 4760 (class 2606 OID 16442)
-- Name: usuarios usuarios_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_nome_key UNIQUE (nome);


--
-- TOC entry 4762 (class 2606 OID 16440)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4775 (class 1259 OID 24611)
-- Name: idx_movimentacoes_categoria; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_movimentacoes_categoria ON public.movimentacoes USING btree (categoria_id);


--
-- TOC entry 4776 (class 1259 OID 24612)
-- Name: idx_movimentacoes_data; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_movimentacoes_data ON public.movimentacoes USING btree (data_movimentacao);


--
-- TOC entry 4777 (class 1259 OID 24609)
-- Name: idx_movimentacoes_tipo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_movimentacoes_tipo ON public.movimentacoes USING btree (tipo);


--
-- TOC entry 4778 (class 1259 OID 24610)
-- Name: idx_movimentacoes_usuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_movimentacoes_usuario ON public.movimentacoes USING btree (usuario_id);


--
-- TOC entry 4786 (class 2620 OID 24636)
-- Name: rules trigger_update_updated_at; Type: TRIGGER; Schema: caixa2025; Owner: caixa_adm
--

CREATE TRIGGER trigger_update_updated_at BEFORE UPDATE ON caixa2025.rules FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


--
-- TOC entry 4785 (class 2620 OID 24578)
-- Name: usuarios update_usuarios_updated_at; Type: TRIGGER; Schema: caixa2025; Owner: postgres
--

CREATE TRIGGER update_usuarios_updated_at BEFORE UPDATE ON caixa2025.usuarios FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- TOC entry 4783 (class 2606 OID 24604)
-- Name: movimentacoes movimentacoes_categoria_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimentacoes
    ADD CONSTRAINT movimentacoes_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.categorias(id) ON DELETE SET NULL;


--
-- TOC entry 4784 (class 2606 OID 24599)
-- Name: movimentacoes movimentacoes_usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimentacoes
    ADD CONSTRAINT movimentacoes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE CASCADE;


-- Completed on 2025-04-30 18:19:45

--
-- PostgreSQL database dump complete
--

